import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/NavBar";
import Footer from "./components/Footer";
import { ContextProvider } from "./context/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bookshelf App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Nav />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
